### ISSUE TITLE
Validate unexpected input

### ISSUE THREAD

**Issue by munHunger** [munHunger/soft-sync#22]
**Is your feature request related to a problem? Please describe.**
If the yml file is slightly malformed it may cause some serious issues

**Describe the solution you'd like**
Add more validation to detect when there are properties that aren't expected

Also the settings should respect the position type

**Additional context**
This is perfectly valid yml
```
settings:
  - path: ~/.config/i3/config2
    content: |-
      exec --no-startup-id "feh --bg-scale ~/.config/wallpaper.jpg"
    position:
      type: END
      when:
      installed:
        - i3
```
but the `when` will ofcourse be ignored and thus it will overwrite everything at path
